# Generated by Django 4.1.5 on 2023-01-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunkaVallalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('eretkeles', models.FloatField(default=0)),
                ('erdekelt', models.CharField(max_length=255)),
                ('azon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MunkaAdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('ertekeles', models.FloatField(default=0)),
                ('azon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Munka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('leiras', models.TextField(default='')),
                ('ertekeles', models.FloatField(default=0)),
                ('helye', models.CharField(default='', max_length=255)),
                ('katt', models.IntegerField(default=0)),
                ('berMin', models.IntegerField()),
                ('berMax', models.IntegerField(null=True)),
                ('munkaKezd', models.DateTimeField()),
                ('munkaNapok', models.TextField()),
                ('publikalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.munkaado')),
            ],
        ),
        migrations.CreateModel(
            name='Jelentkezes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ido', models.DateTimeField()),
                ('berigeny', models.IntegerField(null=True)),
                ('munkaVallalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.munkavallalo')),
                ('munkaltato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.munkaado')),
            ],
        ),
    ]
