# Generated by Django 4.1.5 on 2023-02-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_munkaado_nev'),
    ]

    operations = [
        migrations.AddField(
            model_name='jelentkezes',
            name='munka',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.munka'),
        ),
        migrations.AddField(
            model_name='munkaado',
            name='bemutatkozas',
            field=models.TextField(default='Nem írt bemutatkozást!', null=True),
        ),
        migrations.AddField(
            model_name='munkavallalo',
            name='bemutatkozas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='berigeny',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=-3600),
        ),
        migrations.AlterField(
            model_name='munkavallalo',
            name='erdekelt',
            field=models.CharField(choices=[('var', 'Varrás szabás'), ('prog', 'Programozás'), ('mern', 'Mérnök'), ('webf', 'webfejlesztés'), ('ramo', 'rámolás, pakolás'), ('fuva', 'fuvarozás'), ('erte', 'értékesítés'), ('taka', 'takarítás')], max_length=4),
        ),
    ]
