# Generated by Django 4.1.5 on 2023-02-05 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jelentkezes_munka_munkaado_bemutatkozas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 14, 50, 34, 713170)),
        ),
    ]
