# Generated by Django 4.1.5 on 2023-02-05 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_jelentkezes_ido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munkavallalo',
            name='azon',
        ),
        migrations.RemoveField(
            model_name='jelentkezes',
            name='munkaltato',
        ),
        migrations.AddField(
            model_name='jelentkezes',
            name='bemutatkozas',
            field=models.TextField(default='A jelentkező nem írt leírást.', null=True),
        ),
        migrations.AddField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(default='', upload_to='feltoltottDokumentumok/auth.User'),
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 19, 53, 6, 441197)),
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='munkaVallalo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='munka',
            name='publikalo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MunkaAdo',
        ),
        migrations.DeleteModel(
            name='MunkaVallalo',
        ),
    ]
