# Generated by Django 4.1.5 on 2023-02-06 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_munkavallalo_azon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 14, 47, 17, 953967)),
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to='feltoltottDokumentumok/auth.User'),
        ),
    ]
