# Generated by Django 4.1.5 on 2023-02-06 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jelentkezes_ido_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 15, 43, 52, 728193)),
        ),
    ]
