# Generated by Django 4.1.5 on 2023-02-06 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jelentkezes_ido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='ido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
