# Generated by Django 4.1.5 on 2023-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to='feltoltottDokumentumok/<function FajlUtvonal at 0x00000284B1737600>'),
        ),
    ]
