# Generated by Django 4.1.5 on 2023-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munka',
            name='munkaNapok',
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to='feltoltottDokumentumok/<function FajlUtvonal at 0x00000259ECA82A20>'),
        ),
    ]
