# Generated by Django 4.1.5 on 2023-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_munka_munkanapok_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munka',
            name='ertekeles',
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to='feltoltottDokumentumok/<function FajlUtvonal at 0x000002275B8F2A20>'),
        ),
    ]
