# Generated by Django 4.1.7 on 2023-03-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_jelentkezes_felhid_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='munka',
            options={'ordering': ['-katt']},
        ),
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to='feltoltottDokumentumok/felh_<django.db.models.fields.CharField>/'),
        ),
    ]
