# Generated by Django 4.1.5 on 2023-02-08 13:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_jelentkezes_felhid_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(upload_to=app.models.fajlNevGeneralo),
        ),
    ]
