# Generated by Django 4.1.7 on 2023-03-25 22:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_jelentkezes_melleklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezes',
            name='melleklet',
            field=models.FileField(max_length=255, upload_to=app.models.KonyvtarKezeles),
        ),
    ]
