# Generated by Django 4.1.7 on 2023-04-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_toredek_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
